version: "4"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - app-network

  node1:
    container_name: node1
    hostname: node1
    image: node:18
    command: node index.js
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - app-network

  node2:
    container_name: node2
    hostname: node2
    image: node:18
    command: node index.js
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - app-network

  node3:
    container_name: node3
    hostname: node3
    image: node:18
    command: node index.js
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
